version: '3.7'

services:
  consul:
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul
    command: agent -client=0.0.0.0 -server -bootstrap-expect 1
    ports:
      - 169.254.32.1:8500:8500
  cilium:
    image: docker.io/cilium/cilium:v1.7.3
    command: cilium-agent --kvstore consul --kvstore-opt consul.address=169.254.32.1:8500 -t vxlan --enable-ipv6=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/run/cilium
      - /var/run/docker/netns:/var/run/docker/netns
      - /sys/fs/bpf:/sys/fs/bpf
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
      - "SYS_ADMIN"
    privileged: true
    depends_on:
      - consul
  plugin:
    image: docker.io/cilium/docker-plugin:v1.7.3
    command: cilium-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/run/cilium
      - /run/docker/plugins:/run/docker/plugins
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    depends_on:
      - cilium
