version: '3.7'

services:
  consul:
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul:1.9.0-beta1
    command: agent -client=169.254.32.1 -bind=169.254.32.1 -server -bootstrap-expect 1
    volumes:
      - ./etc/data/consul:/consul/data
    restart: always
    network_mode: "host"
  cilium:
    image: docker.io/cilium/cilium:v1.9.0-rc2
    command: cilium-agent --kvstore consul --kvstore-opt consul.address=169.254.32.1:8500 -t vxlan --enable-ipv6=false --enable-hubble=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker/netns:/var/run/docker/netns
      - /sys/fs/bpf:/sys/fs/bpf
      - ./etc/data/cilium:/var/run/cilium
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
      - "SYS_ADMIN"
    privileged: true
    depends_on:
      - consul
    restart: always
  plugin:
    image: docker.io/cilium/docker-plugin:v1.9.0-rc2
    command: cilium-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ./etc/data/cilium:/var/run/cilium
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    depends_on:
      - cilium
    restart: always
