---
kind: pipeline
type: docker
name: check

platform:
  os: linux
  arch: amd64

steps:
- name: fmt
  image: letfn/drone
  settings:
    task: fmt

- name: lint
  image: letfn/drone
  settings:
    task: lint

...
