version: '3.7'

services:
  openvpn:
    image: letfn/openvpn
    volumes:
      - ./etc/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN
    depends_on:
      - pihole
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.openvpn.entrypoints=openvpn"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`*`)"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=1194"

networks:
  default:
    external:
      name: kitt
