version: '3.7'

services:
  zerotier:
    image: letfn/zerotier
    restart: always
    volumes:
      - ./etc/zerotier/zerotier-one:/var/lib/zerotier-one
      - ./etc/zerotier/config:/data/config
    cap_drop:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    links:
      - traefik
    privileged: true

networks:
  default:
    external:
      name: kitt
