version: '3.7'

services:
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - cloudflared:/etc/cloudflared
    environment:
        - TUNNEL_URL=http://${KITT_TUNNEL_URL}
        - TUNNEL_HOSTNAME=${KITT_TUNNEL_HOSTNAME}
    depends_on:
      - traefik
      - consul
    dns:
      - 1.1.1.1
      - 1.0.0.1

volumes:
  cloudflared:

networks:
  default:
    external:
      name: kitt
