version: '3.7'

services:
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command:
      - -internal=true
      - consul://${CONSUL_IP}:8500
  whoami:
    image: containous/whoami
    ports:
      - 80
    labels:
      - "SERVICE_NAME=whoami"
      - "SERVICE_TAGS=traefik.enable=true,traefik.enable=true,traefik.http.routers.kuard.entrypoints=https,traefik.http.routers.kuard.rule=HostRegexp(`whoami.{domain:.+}`)"
      - "app=hello"
      - "zone=kitt"
  kuard:
    image: gcr.io/kuar-demo/kuard-amd64:blue
    ports:
      - 8080
    labels:
      - "SERVICE_NAME=kuard"
      - "SERVICE_TAGS=traefik.enable=true,traefik.enable=true,traefik.http.routers.kuard.entrypoints=https,traefik.http.routers.kuard.rule=HostRegexp(`kuard.{domain:.+}`)"
      - "app=hello"
      - "zone=kitt"

networks:
  default:
    driver: cilium
    ipam:
      config:
        - subnet: ${KITT_NETWORK}

