version: '3.7'

services:
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command:
      - -internal=true
      - consul://localhost:8500

networks:
  default:
    driver: cilium
    ipam:
      config:
        - subnet: ${KITT_NETWORK}

