version: '3.7'

services:
  traefik:
    image: "traefik:v2.2.7"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.usebindportip=false
      - --providers.consulcatalog=true
      - --providers.consulcatalog.exposedbydefault=false
      - --providers.consulcatalog.endpoint.address=${KITT_IP}:8500
      - --providers.consulcatalog.endpoint.datacenter=dc1
      - --providers.consulcatalog.endpoint.token=${CONSUL_HTTP_TOKEN}
      - --serverstransport.insecureskipverify=true
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.ssh.address=:2222
      - --entrypoints.openvpn.address=:1194
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.le.acme.dnschallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.email=${CF_API_EMAIL}
      - --certificatesResolvers.le.acme.storage=${KITT_ACME_STORAGE:-/etc/traefik/acme/acme.json}
      - --certificatesResolvers.le.acme.dnschallenge.delaybeforecheck=0
      - --certificatesResolvers.le.acme.dnschallenge.resolvers=1.1.1.1
      - --entrypoints.https.address=:443
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.tls.certResolver=le
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    environment:
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/traefik:/etc/traefik"
    depends_on:
      - consul
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - ${KITT_IP}:2222:2222
      - ${KITT_IP}:1194:1194
      - ${KITT_IP}:80:80
      - ${KITT_IP}:443:443
    labels:
      - "id=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.entrypoints=http,https"
      - "traefik.http.routers.traefik-api.rule=HostRegexp(`traefik{domain:.+}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-dash.entrypoints=http,https"
      - "traefik.http.routers.traefik-dash.rule=HostRegexp(`traefik{domain:.+}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
      - "traefik.http.routers.domains.tls=true"
      - "traefik.http.routers.domains.tls.certresolver=le"
      - "traefik.http.routers.domains.tls.domains[0].main=traefik-kitt.${KITT_DOMAIN}"
      - "traefik.http.routers.domains.tls.domains[0].sans=vault.${KITT_DOMAIN},consul.${KITT_DOMAIN}"
  traefik-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    environment:
      - SERVICE_CONFIG=/config/traefik.hcl
      - CENTRAL_CONFIG=/central_config/traefik.hcl
      - CONSUL_HTTP_ADDR=${KITT_IP}:8500
      - CONSUL_GRPC_ADDR=${KITT_IP}:8502
      - CONSUL_HTTP_TOKEN
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "traefik"]
    network_mode: "service:traefik"
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=https://${KITT_TUNNEL_URL}
      - TUNNEL_HOSTNAME=${KITT_TUNNEL_HOSTNAME}
    depends_on:
      - traefik
      - consul
    dns:
      - 1.1.1.1
      - 1.0.0.1
  consul:
    image: consul:1.8.0
    hostname: kitt-consul
    environment:
      - CONSUL_HTTP_TOKEN
    command: [
      "consul","agent",
      "-config-file=/config/dc1.hcl"]
    volumes:
      - "./etc/consul_config:/config"
      - "./etc/consul_dc1:/consul/data"
    ports:
      - "${KITT_IP}:8500:8500"
      - "${KITT_IP}:8502:8502"
      - "${KITT_IP}:8300:8300"
      - "${KITT_IP}:8302:8302/tcp"
      - "${KITT_IP}:8302:8302/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.entrypoints=https"
      - "traefik.http.routers.consul.rule=HostRegexp(`consul.{domain:.+}`)"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
  consul-gateway:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    environment:
      - CONSUL_HTTP_ADDR=${KITT_IP}:8500
      - CONSUL_GRPC_ADDR=${KITT_IP}:8502
      - CONSUL_HTTP_TOKEN
    ports:
      - ${KITT_IP}:4444:443
    command: [
      "consul", "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "{{GetInterfaceIP \"eth0\"}}",
      "-wan-address", "${KITT_IP}:4444",
      "--",
      "-l", "debug"]
    depends_on:
      - consul
  vault:
    image: vault:1.5.0
    hostname: "vault"
    restart: on-failure
    command: [ "sh", "/service" ]
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOG_LEVEL=debug
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
    volumes:
      - ./etc/vault:/config
      - ./vault-service:/service
    ports:
      - ${KITT_IP}:8200:8200
    cap_add:
      - IPC_LOCK
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.rule=HostRegexp(`vault.{domain:.+}`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
    links:
      - consul
    depends_on:
      - consul
      - traefik
  vault-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    environment:
      CONSUL_HTTP_ADDR: ${KITT_IP}:8500
      CONSUL_GRPC_ADDR: ${KITT_IP}:8502
      SERVICE_CONFIG: /config/vault.hcl
      CENTRAL_CONFIG: /central_config/vault.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "vault"]
    network_mode: "service:vault"

networks:
  default:
    external:
      name: kitt
